### PR TITLE
Update app.css

### PR DESCRIPTION
**Pull request by zack4485**
Added consistent line endings
Removed redundant class definitions
Added consistent carriage returns after classes/comments Removed trailing whitespace
Added consistent leading tab whitespace

### CODE REVIEW

**Comment by mythz** [comment]
How was app.css formatted? after running `npm run ui:dev` it goes back to tailwind's default format.

However it's done, it needs to be in the format after `npm run ui:dev` is run, currently it's still generating tailwind's default format.

**Comment by mythz** [comment]
I've added an `format` npm script to convert the tailwindcss generated app.css to use tabs with prettier in this commit:
https://github.com/NetCoreTemplates/razor-ssg/commit/a1033fc0c6d2a7b294361eb66292ee9b0ae05595

In future can any whitespace changes to autogenerated files like this be the result of an automated tool so it doesn't add any friction to the development workflow. 

Also I want to keep this template npm-dep free (i.e. npm install / node_modules isn't required) so `npx` tools should be used (if needed).

**Comment by zack4485** [comment]
Interesting…

I used Visual Studio Code extension Prettier.  While I merged settings from the upstream into my own customized app.css file, the file I committed in the PR was just the de-minified version of the upstream file.

I didn’t observe this behavior on my side else I wouldn’t have submitted the change.

From: Demis Bellot ***@***.***>
Date: Friday, November 1, 2024 at 2:52 AM
To: NetCoreTemplates/razor-ssg ***@***.***>
Cc: zack4485-MSFT ***@***.***>, Author ***@***.***>
Subject: Re: [NetCoreTemplates/razor-ssg] Update app.css (PR #6)

how was app.css formatted? after running npm run ui:dev it goes back to tailwind's default format.

**Comment by zack4485** [comment]
This is better.  Thanks!

Fair request.

From: Demis Bellot ***@***.***>
Date: Friday, November 1, 2024 at 3:20 AM
To: NetCoreTemplates/razor-ssg ***@***.***>
Cc: zack4485-MSFT ***@***.***>, Author ***@***.***>
Subject: Re: [NetCoreTemplates/razor-ssg] Update app.css (PR #6)

I've added an format npm script to convert the tailwindcss generated app.css to use tabs with prettier in this commit:
a1033fc<https://github.com/NetCoreTemplates/razor-ssg/commit/a1033fc0c6d2a7b294361eb66292ee9b0ae05595>

In future can any whitespace changes to autogenerated files like this be the result of an automated tool so it doesn't add any friction to the development workflow.

Also I want to keep this template to be npm-dep free (i.e. npm install / node_modules isn't required) so npx tools are preferred.

**Pull request merged**
